name: Remote deployment
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        passphrase: ${{ secrets.PASSPHRASE }}
        port: ${{ secrets.PORT }}
        key: ${{ secrets.KEY }}
        script: |
          rm -rf testrepo
          git clone https://github.com/marcopaganini/testrepo
          cd testrepo
          git-crypt unlock <(echo "${{ secrets.GIT_CRYPT_KEY }}" | base64 -d)
          cat crypt/*

